#!flask/bin/python
from flask import Flask, render_template, Response
import requests
import json

app = Flask(__name__)

def get_data():
    # Input Variables
    url = 'https://books.zoho.com/api/v3/invoices/100021000000058075' #RESTful URL con invoice_id
    authtoken = '' #Authorization token generated by Zoho
    organization_id = '41622462' # organization_id generated by Zoho

    #Get JSON
    auth = {'authtoken':authtoken,'organization_id':organization_id}
    r = requests.get(url,params=auth)
    invoice = r.json()
    return invoice


@app.route('/')
def index():
    return render_template('index.html')

@app.route('/createjson')
#falta agregar el argumento para buscar el id del invoice unico y asi encontrar el url correcto.
def create_json():
    data=get_data()
    proforma_number = data["invoice"]["invoice_number"]
    customer_name = data["invoice"]["customer_name"]
    address = data["invoice"]["billing_address"]
    #phone_number = data["invoice"]["customer_name"]
    #ruc = data["invoice"]["customer_name"]
    products = data["invoice"]["line_items"]
    fiscal_string = '{"factura":{"cliente":{"empresa":'+"\""+customer_name+"\""+',"direccion":"","telefono":"","ruc":"0"}}}'
    print (fiscal_string)
    fiscal_json = json.dumps(json.loads(fiscal_string))
    return Response(fiscal_json,
            mimetype='application/json',
            headers={'Content-Disposition':'attachment;filename='+proforma_number+'.json'})



if __name__ == '__main__':
    app.run(debug=True)
