#!flask/bin/python
from flask import Flask, render_template, Response
import requests
import json

app = Flask(__name__)

def get_invoice_list():
# Input Variables
    url = 'https://books.zoho.com/api/v3/invoices' #RESTful URL
    authtoken = 'bf3edb14f0a536a594e8c4acf9c0628a' #Authorization token generated by Zoho
    organization_id = '41622462' # organization_id generated by Zoho

    #Get JSON
    auth = {'authtoken':authtoken,'organization_id':organization_id}
    r = requests.get(url,params=auth)
    data = r.json()
    return data

def get_invoice_detail():
    # Input Variables
    url = 'https://books.zoho.com/api/v3/invoices/100021000000058075' #RESTful URL con invoice_id
    authtoken = 'bf3edb14f0a536a594e8c4acf9c0628a' #Authorization token generated by Zoho
    organization_id = '41622462' # organization_id generated by Zoho

    #Get JSON
    auth = {'authtoken':authtoken,'organization_id':organization_id}
    r = requests.get(url,params=auth)
    invoice = r.json()
    return invoice


@app.route('/')
def index():
    invoice_list = get_invoice_list()
    invoice_json = json.dumps(invoice_list)
    return render_template('index.html', invoice_json=invoice_json)


#falta agregar el argumento para buscar el id del invoice unico y asi encontrar el url correcto.
# def parse_invoice_list():
#     data = get_invoice_list()
#
#     proforma_number = data["invoices"][1]["invoice_number"]
#     fiscal_string = {'invoice_number':proforma_number}
#     return fiscal_string

@app.route('/create_invoice_json')
#falta agregar el argumento para buscar el id del invoice unico y asi encontrar el url correcto.
def create_invoice_json():
    data=get_invoice_detail()
    proforma_number = data["invoice"]["invoice_number"]
    customer_name = data["invoice"]["customer_name"]
    address = data["invoice"]["billing_address"]
    #phone_number = data["invoice"]["customer_name"]
    #ruc = data["invoice"]["customer_name"]
    products = data["invoice"]["line_items"]
    fiscal_string = '{"factura":{"cliente":{"empresa":'+"\""+customer_name+"\""+',"direccion":"","telefono":"","ruc":"0"}}}'
    fiscal_json = json.dumps(json.loads(fiscal_string))

    return Response(fiscal_json,
            mimetype='application/json',
            headers={'Content-Disposition':'attachment;filename='+proforma_number+'.json'})



if __name__ == '__main__':
    app.run(debug=True)
