import requests
import json

# Input Variables
url = 'https://books.zoho.com/api/v3/invoices/100021000000058075' #RESTful URL con invoice_id
authtoken = 'bf3edb14f0a536a594e8c4acf9c0628a' #Authorization token generated by Zoho
organization_id = '41622462' # organization_id generated by Zoho

#Get JSON
auth = {'authtoken':authtoken,'organization_id':organization_id}
r = requests.get(url,params=auth)
invoices = r.json()

#Export JSON with ascii set to FALSE for accents
with open('data.json', 'w') as outfile:
  json.dump(invoices, outfile, ensure_ascii=False)
