import requests
import json

# Input Variables
url = 'https://books.zoho.com/api/v3/invoices' #RESTful URL
authtoken = 'bf3edb14f0a536a594e8c4acf9c0628a' #Authorization token generated by Zoho
organization_id = '41622462' # organization_id generated by Zoho

#Get JSON
auth = {'authtoken':authtoken,'organization_id':organization_id}
r = requests.get(url,params=auth)
invoices = r.json()

#Export JSON with ascii set to FALSE for accents
#with open('data.json', 'w') as outfile:
#  json.dump(invoices, outfile, ensure_ascii=False)


#GET THE LIST OF ALL INVOICE IDS

#VALIDATE WHICH ONES NEED PRINTING; USE THE GATOMALO's db to check. USE the invoice  id



#CREATE JSON FOR EACH INVOICE ID USING THE GATO MALO FORMAT


#             "customer_id": "100021000000039399", ------>para guardar en gatomalo por siacaso se modifica el nombre del cliente
#             "customer_name": "MMD Hotel, S.A.", -------> "empresa"
#             "invoice_id": "100021000000058075", ------->para validar con gato malo si ha sido impreso.
#             "invoice_number": "PROF-000070", ----------> hay que crear el numero de referencia interna




{"factura": {
	"cliente":
		{"empresa":" CASA DE EMPEÑOS MAS ME DAN, S.A.","direccion":"Panama","telefono":"265-4444","ruc":"51001-32-319819 DV 01"},
	"productos": [
		{"nombre":"Data Analysis","cantidad":1,"tasa":2,"precio":1500.00}
	]}}


#POST JSON TO GATOMALO THE JSON TO PRINT
  
  
